### ISSUE TITLE
AUC ROC socre seems decent even before learning starts

### ISSUE THREAD

**Issue by seunghyeon528** [talreiss/Mean-Shifted-Anomaly-Detection#7]
Hi, thx for the code!

Actually, I came across with a question, running your soruce code.

I found that AUC ROC socre is already above 90 % even before learning starts.

I guess this is because classifying algorithm (cosine similarity of 2 nearest data) is quiete effective. 

The overall model owes a lot to hard-coded classifying algorithm even rather than deep-learning. 

I'm new to anomaly detection, So I'm wondering if I've understood correctly.

thank you!

**Comment by talreiss** [comment]
Hi,

In prior work ([PANDA](https://arxiv.org/pdf/2010.05903.pdf)) we demonstrated that combining pre-trained features with simple anomaly detection (e.g. kNN) results with great performance.  Since that our feature extractor is a large ResNet pre-trained on the ImageNet dataset, the results are pretty good from starting epoch.

**Comment by seunghyeon528** [comment]
Thx for such kind explnatation.

Hope you have a good day!

2022년 3월 6일 (일) 오전 6:29, talreiss ***@***.***>님이 작성:

**Comment by talreiss** [comment]
Your welcome :)
